### PR TITLE
Password generation profiles

### PR DESCRIPTION
**Pull request by medyakovvit**
Implemented creating of profiles for generating passwords.

### CODE REVIEW

**Comment by raoulh** [comment]
Hi,
Nice work, but it does not build...

```
../src/PasswordProfilesModel.cpp:18:19: error: pasting "=" and "value" does not give a valid preprocessing token
     bool newValue = ##value##.toBool();
```

**Comment by raoulh** [comment]
Actually the macro is wrong, it should be:

```
#define setProfileBoolValue(profile, value, parameter, changed) \
{ \
    bool newValue = value.toBool(); \
    if(profile->get##parameter() == newValue) \
    break; \
    profile->set##parameter(newValue); \
    changed = profile->get##parameter() == newValue; \
}
```

Also I have warnings when building:
```
In file included from D:\Tests\Moolticute\src\PasswordProfilesModel.cpp:1:0:
D:\Tests\Moolticute\src\PasswordProfilesModel.h: In constructor 'PasswordProfile::PasswordProfile()':
D:\Tests\Moolticute\src\PasswordProfilesModel.h:81:26: warning: 'PasswordProfile::m_useLowercase' will be initialized after [-Wreorder]
     bool m_useUppercase, m_useLowercase, m_useDigits, m_useSymbols;
                          ^
D:\Tests\Moolticute\src\PasswordProfilesModel.h:81:10: warning:   'bool PasswordProfile::m_useUppercase' [-Wreorder]
     bool m_useUppercase, m_useLowercase, m_useDigits, m_useSymbols;
          ^
D:\Tests\Moolticute\src\PasswordProfilesModel.cpp:88:1: warning:   when initialized here [-Wreorder]
 PasswordProfile::PasswordProfile() :
 ^
In file included from D:\Tests\Moolticute\src\PasswordProfilesModel.cpp:1:0:
D:\Tests\Moolticute\src\PasswordProfilesModel.h: In constructor 'PasswordProfile::PasswordProfile(const QString&, bool, bool, bool, bool, const QString&)':
D:\Tests\Moolticute\src\PasswordProfilesModel.h:83:13: warning: 'PasswordProfile::m_name' will be initialized after [-Wreorder]
     QString m_name;
             ^
D:\Tests\Moolticute\src\PasswordProfilesModel.h:80:10: warning:   'bool PasswordProfile::m_editable' [-Wreorder]
     bool m_editable;    /*! False for builtin profiles, true for user created profiles */
          ^
D:\Tests\Moolticute\src\PasswordProfilesModel.cpp:98:1: warning:   when initialized here [-Wreorder]
 PasswordProfile::PasswordProfile(const QString &name,
 ^
In file included from D:\Tests\Moolticute\src\PasswordProfilesModel.cpp:1:0:
D:\Tests\Moolticute\src\PasswordProfilesModel.h:81:26: warning: 'PasswordProfile::m_useLowercase' will be initialized after [-Wreorder]
     bool m_useUppercase, m_useLowercase, m_useDigits, m_useSymbols;
                          ^
D:\Tests\Moolticute\src\PasswordProfilesModel.h:81:10: warning:   'bool PasswordProfile::m_useUppercase' [-Wreorder]
     bool m_useUppercase, m_useLowercase, m_useDigits, m_useSymbols;
          ^
D:\Tests\Moolticute\src\PasswordProfilesModel.cpp:98:1: warning:   when initialized here [-Wreorder]
 PasswordProfile::PasswordProfile(const QString &name,
 ^
In file included from D:\Tests\Moolticute\src\PasswordProfilesModel.cpp:1:0:
D:\Tests\Moolticute\src\PasswordProfilesModel.h: In constructor 'PasswordProfile::PasswordProfile(const QString&)':
D:\Tests\Moolticute\src\PasswordProfilesModel.h:83:13: warning: 'PasswordProfile::m_name' will be initialized after [-Wreorder]
     QString m_name;
             ^
D:\Tests\Moolticute\src\PasswordProfilesModel.h:80:10: warning:   'bool PasswordProfile::m_editable' [-Wreorder]
     bool m_editable;    /*! False for builtin profiles, true for user created profiles */
          ^
D:\Tests\Moolticute\src\PasswordProfilesModel.cpp:113:1: warning:   when initialized here [-Wreorder]
 PasswordProfile::PasswordProfile(const QString &name) :
 ^
D:\Tests\Moolticute\src\PasswordProfilesModel.cpp: At global scope:
D:\Tests\Moolticute\src\PasswordProfilesModel.cpp:325:56: warning: unused parameter 'parent' [-Wunused-parameter]
 int PasswordProfilesModel::rowCount(const QModelIndex &parent) const
                                                        ^
```

Could you please fix those, then I can merge your work.
Thanks!

**Comment by medyakovvit** [comment]
Hi.
Yes, you are right. Why i did that. I will fix warnings.

**Comment by raoulh** [comment]
Merged, thanks a lot!

**Pull request closed without merging**
