### PR TITLE
Russian translation and fixes for compiling errors

### PR DESCRIPTION
**Pull request by medyakovvit**
Added translation files to russian. Translations is not full for now.

### CODE REVIEW

**Comment by raoulh** [comment]
Thanks !

**Comment by limpkin** [comment]
@medyakovvit did you receive your device? :)

**Comment by medyakovvit** [comment]
@limpkin not yet, somewhere at customs) I will be on vacation from 15 to 24 of Semtember. I hope it will be at local post office when i return.

**Comment by limpkin** [comment]
@medyakovvit ok! in the mean time i'll give you a very interesting and hard task ;)

**Comment by medyakovvit** [comment]
@limpkin Nice!

**Pull request merged**
